CC = gcc
CFLAGS = -Wall -std=c11 
all: number_converter.o boot.o

number_converter.o: number_converter.c number_converter.h
	$(CC) $(CFLAGS) -c number_converter.c

boot.o: boot.c
	$(CC) $(FLAGS) -c boot.c
